export const actions = {
  DARK_MODE_ON: "DARK_MODE_ON",
  DARK_MODE_OFF: "DARK_MODE_OFF",
  INPUT_CHANGE: "INPUT_CHANGE",
  ADD_TASK: "ADD_TASK",
  DROP_TASK: "DROP_TASK",
  TOGGLE_TASK: "TOGGLE_TASK",
  DELETE_TASK: "DELETE_TASK",
  CLEAR_COMPLETED: "CLEAR_COMPLETED",
  FILTER_ACTIVE: "FILTER_ACTIVE",
  FILTER_ALL: "FILTER_ALL",
  FILTER_COMPLETED: "FILTER_COMPLETED",
  REORDER: "REORDER",
};
